sudo: false

language: cpp

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - cmake
      - g++-6
      - clang++-3.9

env:
  global:
    # Penguin settings
    - PENGUIN_ROOT=$TRAVIS_BUILD_DIR
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PENGUIN_ROOT/lib


branches:
  only:
    - develop
    - master

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-6

    - compiler: clang
      env: COMPILER=clang++


script:
  - export CXX=${COMPILER}
  - $CXX --version
  - cmake --version
  - cmake .
  - make -j2
  - ctest -j2
