branches:
  only:
  - master
  - develop

os: Visual Studio 2017

clone_depth: 10

install:
  - mkdir ext
  - cd ext
  - git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - git clone -b Latest_Micro --depth 1 git://github.com/DOCGroup/ACE_TAO.git
  - cd ..
  - set MPC_ROOT=%CD%\ext\MPC
  - set ACE_ROOT=%CD%\ext\ACE_TAO\ACE
  - set TAO_ROOT=%CD%\ext\ACE_TAO\TAO
  - set PENGUIN_ROOT=%CD%
  - set PATH=%ACE_ROOT%\lib:%PATH%
  - set PATH=%ACE_ROOT%\bin:%PATH%
  - set PATH=%PENGUIN_ROOT%\lib:%PATH%
  - set PATH=%PENGUIN_ROOT%\bin:%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - copy %PENGUIN_ROOT%\build\config.h %ACE_ROOT%\ace
  - copy %PENGUIN_ROOT%\build\default.features %ACE_ROOT%\bin\MakeProjectCreator\config
  - perl %ACE_ROOT%\bin\mwc.pl -type vs2017 %PENGUIN_ROOT%\Penguin_CI.mwc

platform:
  - x64

configuration:
  - Debug

build:
  parallel: true

build_script:
  - msbuild "Penguin_CI.sln" /m /p:Configuration=Debug;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test: off