branches:
  only:
  - master
  - develop

os: Visual Studio 2017

clone_depth: 10

install:
  - set PENGUIN_ROOT=%CD%
  - set PATH=%PENGUIN_ROOT%\lib;%PATH%
  - set PATH=%PENGUIN_ROOT%\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - msbuild /version
  - cmake --version
  - cmake -G "Visual Studio 15 2017 Win64"

platform:
  - x64

configuration:
  - Debug
  - Release

build:
  project: "Penguin.sln"
  parallel: true
  verbosity: minimal

test_script:
 - cmd: ctest -C %CONFIGURATION%
