branches:
  only:
  - master
  - develop

os: Visual Studio 2017

clone_depth: 10

install:
  - set PENGUIN_ROOT=%CD%
  - set PATH=%PENGUIN_ROOT%\lib:%PATH%
  - set PATH=%PENGUIN_ROOT%\bin:%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - cmake -G "Visual Studio 15 2017 Win64"

platform:
  - x64

configuration:
  - Debug

build:
  parallel: true

build_script:
  - msbuild "Penguin.sln" /m /p:Configuration=Debug;Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test: off